exports.seed = async function (knex) {
  await knex('beans').insert([
    {
      id: 1001,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'medium',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Supreme blend',
      image_url: '',
    },
    {
      id: 1002,
      roaster_id: 3,
      region: 'Papua New Guinea | Honduras | Ethiopia | Sumatra',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Forest fruit | Cacao',
      name: 'Aotea blend',
      image_url: '',
    },
    {
      id: 1003,
      roaster_id: 3,
      region: 'Ethiopia | Timor Leste | Honduras | D.R. Congo',
      process: 'Washed',
      roast_degree: 'medium',
      flavour_profile: 'Chocolate | Caramel | Spice',
      name: 'Mahana blend',
      image_url: '',
    },
    {
      id: 1004,
      roaster_id: 1,
      region: 'South America',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Maltesers & Caramel | Smooth & Creamy',
      name: 'South blend',
      image_url: '',
    },
    {
      id: 1005,
      roaster_id: 2,
      region: 'Brazil | Colombia ',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Sweet, balanced and complex.',
      name: 'Allpress Espresso Blend',
      image_url: '',
    },
    {
      id: 1006,
      roaster_id: 5,
      region: 'Rwanda | Colombia | Timor-Leste.',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Orange | Caramel | Cacao nib',
      name: 'Bomber - Original blend',
      image_url: '',
    },
    {
      id: 1007,
      roaster_id: 1,
      region: 'Brazil | Colombia | Papua New Guiena',
      process: 'Washed',
      roast_degree: 'dark',
      flavour_profile: 'Big, fat and chocolatey',
      name: 'A.R.T. Espresso Roast',
      image_url: '',
    },
    {
      id: 1008,
      roaster_id: 5,
      region: 'Rwanda | Colombia | Brazil.',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Orange | Caramel | Cacao nib',
      name: 'Bomber - Original blend',
      image_url: '',
    },
    {
      id: 1009,
      roaster_id: 5,
      region: 'Rwanda | Colombia | Timor-Leste',
      process: 'Washed',
      roast_degree: 'dark',
      flavour_profile: 'Buttercream | Brown sugar | Macadamia nut',
      name: 'B2 - Milk blend',
      image_url: '',
    },
    {
      id: 1010,
      roaster_id: 8,
      region: 'Colombia | Nicaagura | Ethiopia',
      process: 'Washed',
      roast_degree: 'dark',
      flavour_profile: 'Chocolate | Wild berry | Chocolate',
      name: 'Hodson blend',
      image_url: '',
    },
  ])
}
