exports.seed = async function (knex) {
  await knex('beans').insert([
    {
      id: 1001,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Holiday blend',
    },
    {
      id: 1002,
      roaster_id: 3,
      region: 'Aotea Blend',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Aotea blend',
    },
    {
      id: 1003,
      roaster_id: 3,
      region: 'Mahana Blend',
      process: 'Washed',
      roast_degree: 'medium',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Mahana blend',
    },
    {
      id: 1004,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Holiday blend',
    },
    {
      id: 1005,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Holiday blend',
    },
    {
      id: 1006,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Holiday blend',
    },
    {
      id: 10017,
      roaster_id: 1,
      region: 'Central American',
      process: 'Washed',
      roast_degree: 'value',
      flavour_profile: 'Milk Chocolate & Citrus | Sweet & Complex',
      name: 'Holiday blend',
    },
  ])
}
